### PR TITLE
feat: use debug for output messages

### PR DESCRIPTION
**Pull request by KunalSaini**

### CODE REVIEW

**Comment by mgwelch** [comment]
I don't know. I reviewed the documentation for `debug` and it seems like it is best fit for actual debug messages that a developer might turn on for debugging purposes. The messages I'm outputting in this library aren't really debug messages for a developer. They are strings that are meant for any consuming application to write to the console to assist the user.

Now, I can see that there'd be a way to use `debug` for my purposes but it doesn't really seem like it's then being used as intended.

It might actually be a better fit for me to 

1. return library defined error codes for each error we recognize
2. potentially include a dictionary of strings that correspond to those error code
3. Update the consuming applications that I have to console.log the strings based on error code

**Comment by mgwelch** [comment]
Here's where I see (just from looking at the documentation) some conflicts between debug messages and user error messages:

1. the scoping of all messages to a namespace. I supposed I could pass empty string
2. There's a duration appended to each output message

**Comment by mgwelch** [comment]
Example output from a sample app:

```shell
$ node local/launch.js 
  nodekit Error: Unable to login, Please double check you used the correct credentials +0ms
```

**Comment by mgwelch** [comment]
So I think I'd prefer a different solution. Perhaps the one I outlined above. Just define an enumeration of detected errors and then update each method to either a) return ErrorOrValue responses or b) throw errors with error codes as defined by the enumeration.

With specific error codes being return then the client applications can write out whatever they want to the user.

**Comment by mgwelch** [comment]
The other reason to not use `debug` for **this** use case is that we may want to actually use `debug` for actual debug messages.

**Comment by KunalSaini** [comment]
> I don't know. I reviewed the documentation for debug and it seems like it is best fit for actual debug messages that a developer might turn on for debugging purposes

agreed, that's exactly the purpose of debug. A developer writing "awesome new UI" for metasys will need to figure out, why a call to one of your function is returning unexpected data (only 10 row, an error , something else).  He/She might have questions like, how much time does it take to get auth token. vs something there code is doing with the auth token.

> The messages I'm outputting in this library aren't really debug messages for a developer. They are strings that are meant for any consuming application to write to the console to assist the user

well, if its a "library", then what you are trying to do is difficult, as an author of the "awesome new UI" I would like to control how i communicate details to my users, they might not be looking at console. 
However if this code is just a bunch of reference "scripts" and not a npm "library", then may be outputting to console is fine.

 > Just define an enumeration of detected errors and then update each method to either a) return ErrorOrValue responses.

👍 

> or b) throw errors with error codes as defined by the enumeration

👎 

>The other reason to not use debug for this use case is that we may want to actually use debug for actual debug messages

I understood the need mentioned in the https://github.com/metasys-server/nodekit/issues/3 for the use case of helping the developers using this "library" figure out whats wrong. 

In essence, I will close the PR, since this is not the use case you where looking for.

FYI, we should be doing all this good conversation in the "issue" rather then the PR, for documentation purpose.

**Comment by michaelgwelch** [comment]
> I would like to control how i communicate details to my users,

Exactly! Hence the reason I wrote the issue

> FYI, we should be doing all this good conversation in the "issue" rather then the PR, for documentation purpose.

Indeed

**Comment by mgwelch** [comment]
> I would like to control how i communicate details to my users,

Exactly! Hence the reason I wrote the issue

> FYI, we should be doing all this good conversation in the "issue" rather then the PR, for documentation purpose.

Indeed

**Pull request closed without merging**
